package:
  name: plons
  version: "0.0.5"

about:
  home: "https://github.com/Ensor-code/plons"
  license: GPLv3
  license_file: LICENSE
  summary: PLOtting tool for Nice Simulations

source:
  path: ../

requirements:
  build:
    - python[version='>=3.7,<3.11']
    - setuptools
    - wheel
    - pip

  run:
    - python[version='>=3.7,<3.11']
    - matplotlib
    - healpy
    - scipy
    - astropy
    - numpy>=1.17
    - numba

