package:
  name: plons
  version: "0.0.28"

about:
  home: "https://github.com/Ensor-code/plons"
  license: GPLv3
  license_file: LICENSE
  summary: PLOtting tool for Nice Simulations

source:
  path: ../

build:
  noarch: python
  script: "{{ PYTHON }} -m pip install --no-deps ."

requirements:
  host:
    - "python>=3.7,<=3.13"
    - setuptools
    - wheel
    - pip

  run:
    - "python>=3.7,<=3.13"
    - matplotlib
    - healpy
    - scipy
    - numpy>=1.17
